version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: export-india-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: export_india
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - export-india-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: export-india-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - export-india-network

  # Main Application
  app:
    build: .
    container_name: export-india-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/export_india?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 30d
      FRONTEND_URL: http://localhost:3000
      
      # Email Configuration
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: false
      SMTP_USER: your-email@gmail.com
      SMTP_PASS: your-app-password
      FROM_EMAIL: ExportIndia <noreply@exportindia.com>
      
      # File Upload
      MAX_FILE_SIZE: 5242880
      UPLOAD_PATH: ./uploads
      
      # Payment Gateways (Configure as needed)
      RAZORPAY_KEY_ID: your_razorpay_key_id
      RAZORPAY_KEY_SECRET: your_razorpay_secret
      PAYPAL_CLIENT_ID: your_paypal_client_id
      PAYPAL_CLIENT_SECRET: your_paypal_secret
      
      # External APIs
      GOOGLE_MAPS_API_KEY: your_google_maps_key
      EXCHANGE_RATE_API_KEY: your_exchange_rate_key
    ports:
      - "5000:5000"
    volumes:
      - app_uploads:/app/backend/uploads
      - app_logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - export-india-network
    healthcheck:
      test: ["CMD", "node", "backend/scripts/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local

networks:
  export-india-network:
    driver: bridge